name: Create Cloud Deploy Release
# uses: google-github-actions/create-cloud-deploy-release@v1.1.1
on: 
    push: 
      branches: 
        - main
jobs:
    deploy:
      permissions:
        contents: 'read'
        id-token: 'write'
  
      # ...

      runs-on: ubuntu-latest
      steps:
        - name: 'Checkout'
          uses: 'actions/checkout@v3'
  
        - uses: 'google-github-actions/auth@v2'
          with:
                workload_identity_provider: 'projects/840134438674/locations/global/workloadIdentityPools/taskprojectpool/providers/GitHub'
                service_account: '840134438674-compute@developer.gserviceaccount.com'
  
        - uses: 'google-github-actions/deploy-cloudrun@v2'
          with:
              image: 'us-east5-docker.pkg.dev/np-task-project/cloud-run-source-deploy/task_project/task-project'
              service: 'task-project'